### ISSUE TITLE
fit comment unique IDs

### ISSUE THREAD

**Issue by djosey** [djosey/rdtparse#1]
comment unique identifiers in the data seem to sometimes have different numbers of characters in the string.  test this by sampling the comments column to determine comment sizing patterns, and re-fit the script to grab only the appropriate section of the unique identifier.

**Comment by djosey** [comment]
ie look at these lines

ct5wd, ct5ud"}, 
ct5wi"}, ct5so, 
ct5wj, ct0lt,
ct5wk, t1z0"},
ct5wl, t5ns,
ct5wn"}, t3v1,

we're getting quotations and end curly brackets on some items.

**Comment by djosey** [comment]
ah this seems to be a side effect of the line break issue, can fix

**Comment by eddiechilton** [comment]
I'll work on this before our meeting tomorrow. I'm pretty sure none of the comment IDs have double quotation marks, so I think I can just 1) change the searchStringA variable to just a double quotation mark. 2) remove the "if lbki < sreA..." statement since even if the comment id is right before a "}" it will terminate at the second double quote before it gets to the curly bracket/linebreak.

**Comment by djosey** [comment]
just fixed it, there was an issue with my loop and honestly I'm not at all certain how the script was working right in the first place. wew
